services:

  minube:                                          
    image: owncloud/server:${OWNCLOUD_VERSION} 
    restart: always
    ports:
      - 8080-8082:8080                          
    depends_on:
      - mariadb_slave
      - redis
    environment:                                                 
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS}
      - OWNCLOUD_DB_TYPE=${OWNCLOUD_DB_TYPE}
      - OWNCLOUD_DB_NAME=${OWNCLOUD_DB_NAME}
      - OWNCLOUD_DB_USERNAME=${OWNCLOUD_DB_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - OWNCLOUD_DB_HOST=${OWNCLOUD_DB_HOST}
      - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=${OWNCLOUD_MYSQL_UTF8MB4}
      - OWNCLOUD_REDIS_ENABLED=${OWNCLOUD_REDIS_ENABLED}
      - OWNCLOUD_REDIS_HOST=${OWNCLOUD_REDIS_HOST}
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - datos:/mnt/data                           
    deploy:
      replicas: 3                                  

  haproxy:                                           
    image: haproxytech/haproxy-alpine
    container_name: haproxy
    volumes:
      - ./haconfig:/usr/local/etc/haproxy:ro          
    restart: always                                   
    ports:
      - 80:80
      - 8404:8404
    depends_on:
      - minube                                      

  mariadb_master:
    image: mariadb
    container_name: db_master
    restart: always
    environment:                                
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M", "--server-id=1", "--log-bin=master-bin", "--log-bin-index=master-bin.index"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_master:/var/lib/mysql                                        
      - ./sqlmaster:/docker-entrypoint-initdb.d

  mariadb_slave:
    image: mariadb
    container_name: db_slave
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M", "--server-id=2", "--relay-log=slave-relay-bin", "--relay-log-index=slave-relay-bin.index", "--log-bin=slave-bin", "--log-bin-index=slave-bin.index", "--relay-log-recovery=1", "--slave-net-timeout=60"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_slave:/var/lib/mysql                                    
      - ./sqlslave:/docker-entrypoint-initdb.d
    depends_on:
      - mariadb_master

  redis:
    image: redis
    container_name: redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data  

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/ldapvol/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_TLS_CRT_FILENAME=${LDAP_TLS_CRT_FILENAME}
      - LDAP_TLS_KEY_FILENAME=${LDAP_TLS_KEY_FILENAME}
      - LDAP_TLS_CA_CRT_FILENAME=${LDAP_TLS_CA_CRT_FILENAME}
      - LDAP_READONLY_USER=${LDAP_READONLY_USER}
      - LDAP_READONLY_USER_USERNAME=${LDAP_READONLY_USER_USERNAME}
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
      
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "7777:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=${PHPLDAPADMIN_LDAP_HOSTS}
      - PHPLDAPADMIN_HTTPS=${PHPLDAPADMIN_HTTPS}
    depends_on:
      - openldap

volumes:
  datos:          
  mysql_master:
  mysql_slave:
  redis: